### ISSUE TITLE
Error on open Bench Settings

### ISSUE THREAD

**Issue by mhbu50** [frappe/bench_manager#48] opened 2018-05-07 10:59 UTC
I get this error when I open Bench Settings:

 `Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 223, in sync_all
    sync_sites()
  File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 63, in sync_sites
    site_dirs = update_site_list()
  File "/home/frappe/frappe-bench/apps/bench_manager/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py", line 114, in update_site_list
    for root, dirs, files in os.walk(".", topdown=True):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 299, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 299, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 299, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/frappe/frappe-bench/env/lib/python2.7/os.py", line 289, in walk
    if isdir(join(top, name)):
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py", line 46, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-30: ordinal not in range(128)`

**Comment by mhbu50** [comment] 2018-05-25 02:19
I fix this error with this command:

```
sudo locale-gen en_US en_US.UTF-8 hu_HU hu_HU.UTF-8
sudo dpkg-reconfigure locales
```

**Comment by codingCoffee** [comment] 2018-06-03 22:59
I've sent some fixes #52
Just check if the issue persists and if it does, can you tell me the following:
1. are you using python2 or pyton3
2. list the contests of the `sites` directory in `frappe-bench`

**Comment by mhbu50** [comment] 2018-06-04 00:04
@codingCoffee Thanks for your update, the error is gone but it hangs forever and gives request timeout!

![image](https://user-images.githubusercontent.com/11526423/40892786-d08025ee-67a3-11e8-96ae-8cc5a8ab8f40.png)

1. I am using Python 2.7.6

**Comment by codingCoffee** [comment] 2018-06-04 06:50
Do you get any error message in the browser console or `logs/bench.log` or `logs/frappe.log` ? If yes, can you post it here. I'm not able to replicate the error.

**Comment by mhbu50** [comment] 2018-06-04 10:37
I just get this in browser console: 

`jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
libs.min.js?ver=1527770933.0:7284 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:6080)
    at ra (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:22526)
    at ca (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:25610)
    at La (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:25477)
    at ha (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:25196)
    at Ya (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:25935)
    at m (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7284:3828)
    at Function.s [as tz] (https://erp.accuratesystems.com.sa/assets/js/libs.min.js?ver=1527770933.0:7291:3573)
    at prettyDate (https://erp.accuratesystems.com.sa/assets/js/desk.min.js?ver=1527770933.0:7406:21)
    at HTMLSpanElement.<anonymous> (https://erp.accuratesystems.com.sa/assets/js/desk.min.js?ver=1527770933.0:7454:17)
D @ libs.min.js?ver=1527770933.0:7284`

**Comment by codingCoffee** [comment] 2018-06-04 11:35
Can you open the network tab in the browser console and send a screenshot of the last query in red

**Comment by mhbu50** [comment] 2018-06-04 11:38
![image](https://user-images.githubusercontent.com/11526423/40915479-e748c00e-6804-11e8-90f7-aad31a01d775.png)

**Comment by codingCoffee** [comment] 2018-06-04 11:40
Can you please highlight the 2nd one... the one appearing in red and send a screenshot again

**Comment by mhbu50** [comment] 2018-06-04 11:40
Same thing

**Comment by codingCoffee** [comment] 2018-06-05 07:56
Most likely it is occurring due to large number of sites present. I have enqueued it as a background job. Can you update and verify if the issue is fixed.

**Comment by codingCoffee** [comment] 2018-06-11 13:16
@mhbu50 I presume this has been resolved. Closing issue. If it isn't fixed feel free to open again.

**Closed as completed** 2018-06-11 13:16 UTC
Labels: reply-needed
